apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-api
  namespace: wiz

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-api

  template:
    metadata:
      labels:
        app: todo-api

    spec:
      containers:
      - name: todo-api

        image: 369504341517.dkr.ecr.ap-south-1.amazonaws.com/wiz-todo-api:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"

        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_URI

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5